name: Upload website to S3 bucket

on:
    push:
        branches:
            - main
            - develop
            - uat

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup AWS Creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ SECRETS.aws-access-key-id }}
                aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
                aws-region: ${{ secrets.AWS_REGION}}

            - name: Install dependencies and run tests
              run: npm install && npm run test

            - name: Build react application
              run: REACT_APP_API_KEY=${{ secrets.API_KEY }} npm run build

            - name: Deploy static files from build folder to S3 bucket
              run: aws s3 async ./build/ s3://${{secrets.BUCKET}} --delete
